# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - "./data/data.backup:/var/lib/postgres/data"
  #  
  #aikoapi:
  #  image: aikoapi
  #  build:
  #    context: .
  #    dockerfile: AikoAPI/Dockerfile
  #  ports:
  #    - 5001:5001
  #    - 5000:5000

  #aikofrontend:
  #  image: aikofrontend
  #  build:
  #    context: .
  #    dockerfile: AikoFrontEnd/Dockerfile
  #  ports:
  #    - 5003:5003
  #    - 5002:5002

