#pragma checksum "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\Shared\ForeignKeyConstraintViolation.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "91e1a994479c6980cecb3ab31a6f43021f5829a9"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(WebApp.Pages.Shared.Pages_Shared_ForeignKeyConstraintViolation), @"mvc.1.0.razor-page", @"/Pages/Shared/ForeignKeyConstraintViolation.cshtml")]
namespace WebApp.Pages.Shared
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\_ViewImports.cshtml"
using WebApp;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"91e1a994479c6980cecb3ab31a6f43021f5829a9", @"/Pages/Shared/ForeignKeyConstraintViolation.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"54a580a236bf4511f2b8e02a6219a9844921dafb", @"/Pages/_ViewImports.cshtml")]
    public class Pages_Shared_ForeignKeyConstraintViolation : global::Microsoft.AspNetCore.Mvc.RazorPages.Page
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 3 "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\Shared\ForeignKeyConstraintViolation.cshtml"
  
    ViewData["Title"] = "Erro de chaves";

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n<h1>Não é possível realizar a operação porque o recurso tem dependências à outras tabelas.</h1>\r\n");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<WebApp.Pages.Shared.ForeignKeyConstraintViolationModel> Html { get; private set; }
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<WebApp.Pages.Shared.ForeignKeyConstraintViolationModel> ViewData => (global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<WebApp.Pages.Shared.ForeignKeyConstraintViolationModel>)PageContext?.ViewData;
        public WebApp.Pages.Shared.ForeignKeyConstraintViolationModel Model => ViewData.Model;
    }
}
#pragma warning restore 1591
