#pragma checksum "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\EquipmentModelStateHourly_Earnings\Details.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "7fa96f013b92753d27b8136ac6668eb5537489ec"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(WebApp.Pages.EquipmentModelStateHourly_Earnings.Pages_EquipmentModelStateHourly_Earnings_Details), @"mvc.1.0.razor-page", @"/Pages/EquipmentModelStateHourly_Earnings/Details.cshtml")]
namespace WebApp.Pages.EquipmentModelStateHourly_Earnings
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\_ViewImports.cshtml"
using WebApp;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"7fa96f013b92753d27b8136ac6668eb5537489ec", @"/Pages/EquipmentModelStateHourly_Earnings/Details.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"54a580a236bf4511f2b8e02a6219a9844921dafb", @"/Pages/_ViewImports.cshtml")]
    public class Pages_EquipmentModelStateHourly_Earnings_Details : global::Microsoft.AspNetCore.Mvc.RazorPages.Page
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
#nullable restore
#line 4 "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\EquipmentModelStateHourly_Earnings\Details.cshtml"
  
    ViewData["Title"] = "Details";

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n<h1>Details</h1>\r\n\r\n<div>\r\n    <h4>EquipmentModelStateHourlyEarnings</h4>\r\n    <hr />\r\n    <dl class=\"row\">\r\n        <dt class=\"col-sm-2\">\r\n            ");
#nullable restore
#line 15 "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\EquipmentModelStateHourly_Earnings\Details.cshtml"
       Write(Html.DisplayNameFor(model => model.EquipmentModelStateHourlyEarnings.Equipment_state_id));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n        </dt>\r\n        <dd class=\"col-sm-10\">\r\n            ");
#nullable restore
#line 18 "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\EquipmentModelStateHourly_Earnings\Details.cshtml"
       Write(Html.DisplayFor(model => model.EquipmentModelStateHourlyEarnings.Equipment_state_id));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n        </dd>\r\n    </dl>\r\n</div>\r\n");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<WebApp.Pages.EquipmentModelStateHourly_Earnings.DetailsModel> Html { get; private set; }
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<WebApp.Pages.EquipmentModelStateHourly_Earnings.DetailsModel> ViewData => (global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<WebApp.Pages.EquipmentModelStateHourly_Earnings.DetailsModel>)PageContext?.ViewData;
        public WebApp.Pages.EquipmentModelStateHourly_Earnings.DetailsModel Model => ViewData.Model;
    }
}
#pragma warning restore 1591
