#pragma checksum "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\Equipments\LastPosition.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "c03c339ce5ba78ceb3d3fdd5ff5770f63e84d463"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(WebApp.Pages.Equipments.Pages_Equipments_LastPosition), @"mvc.1.0.razor-page", @"/Pages/Equipments/LastPosition.cshtml")]
namespace WebApp.Pages.Equipments
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\_ViewImports.cshtml"
using WebApp;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"c03c339ce5ba78ceb3d3fdd5ff5770f63e84d463", @"/Pages/Equipments/LastPosition.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"54a580a236bf4511f2b8e02a6219a9844921dafb", @"/Pages/_ViewImports.cshtml")]
    public class Pages_Equipments_LastPosition : global::Microsoft.AspNetCore.Mvc.RazorPages.Page
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
#nullable restore
#line 4 "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\Equipments\LastPosition.cshtml"
  
    ViewData["Title"] = "LastPosition";

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n\r\n<h1>Last Position</h1>\r\n\r\n<table class=\"table\">\r\n    <thead>\r\n        <tr>\r\n            <th>\r\n                ");
#nullable restore
#line 15 "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\Equipments\LastPosition.cshtml"
           Write(Html.DisplayNameFor(model => model.EquipmentPositionLastHistory[0].Equipment_id));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n            </th>\r\n            <th>\r\n                ");
#nullable restore
#line 18 "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\Equipments\LastPosition.cshtml"
           Write(Html.DisplayNameFor(model => model.EquipmentPositionLastHistory[0].Equipment_model_id));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n            </th>\r\n            <th>\r\n                ");
#nullable restore
#line 21 "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\Equipments\LastPosition.cshtml"
           Write(Html.DisplayNameFor(model => model.EquipmentPositionLastHistory[0].Equipment_model_name));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n            </th>\r\n            <th>\r\n                ");
#nullable restore
#line 24 "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\Equipments\LastPosition.cshtml"
           Write(Html.DisplayNameFor(model => model.EquipmentPositionLastHistory[0].Equipment_name));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n            </th>\r\n            <th>\r\n                ");
#nullable restore
#line 27 "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\Equipments\LastPosition.cshtml"
           Write(Html.DisplayNameFor(model => model.EquipmentPositionLastHistory[0].Equipment_position_lat));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n            </th>\r\n            <th>\r\n                ");
#nullable restore
#line 30 "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\Equipments\LastPosition.cshtml"
           Write(Html.DisplayNameFor(model => model.EquipmentPositionLastHistory[0].Equipment_position_lon));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n            </th>\r\n            <th>\r\n                ");
#nullable restore
#line 33 "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\Equipments\LastPosition.cshtml"
           Write(Html.DisplayNameFor(model => model.EquipmentPositionLastHistory[0].Date));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n            </th>\r\n            <th></th>\r\n        </tr>\r\n    </thead>\r\n    <tbody>\r\n");
#nullable restore
#line 39 "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\Equipments\LastPosition.cshtml"
         foreach (var item in Model.EquipmentPositionLastHistory)
        {

#line default
#line hidden
#nullable disable
            WriteLiteral("        <tr>\r\n            <td>\r\n                ");
#nullable restore
#line 43 "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\Equipments\LastPosition.cshtml"
           Write(Html.DisplayFor(modelItem => item.Equipment_id));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");
#nullable restore
#line 46 "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\Equipments\LastPosition.cshtml"
           Write(Html.DisplayFor(modelItem => item.Equipment_model_id));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");
#nullable restore
#line 49 "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\Equipments\LastPosition.cshtml"
           Write(Html.DisplayFor(modelItem => item.Equipment_model_name));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");
#nullable restore
#line 52 "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\Equipments\LastPosition.cshtml"
           Write(Html.DisplayFor(modelItem => item.Equipment_name));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");
#nullable restore
#line 55 "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\Equipments\LastPosition.cshtml"
           Write(Html.DisplayFor(modelItem => item.Equipment_position_lat));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");
#nullable restore
#line 58 "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\Equipments\LastPosition.cshtml"
           Write(Html.DisplayFor(modelItem => item.Equipment_position_lon));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");
#nullable restore
#line 61 "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\Equipments\LastPosition.cshtml"
           Write(Html.DisplayFor(modelItem => item.Date));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n            </td>\r\n        </tr>\r\n");
#nullable restore
#line 64 "C:\Users\Luyeye Henri\Documents\LH\Teste\AIKO\code\AIKO_TestProject\WebApp\Pages\Equipments\LastPosition.cshtml"
        }

#line default
#line hidden
#nullable disable
            WriteLiteral("    </tbody>\r\n</table>");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<WebApp.Pages.Equipments.LastPositionModel> Html { get; private set; }
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<WebApp.Pages.Equipments.LastPositionModel> ViewData => (global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<WebApp.Pages.Equipments.LastPositionModel>)PageContext?.ViewData;
        public WebApp.Pages.Equipments.LastPositionModel Model => ViewData.Model;
    }
}
#pragma warning restore 1591
